// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2019.subsystems;


import org.usfirst.frc4579.Robot2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.smartdashboard.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class BallLifter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Encoder encoder;
    private Spark lifterMotor;
    private PIDController ballLifter_PID;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public BallLifter() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        encoder = new Encoder(1, 2, false, EncodingType.k4X);
        addChild("encoder",encoder);
        encoder.setDistancePerPulse(1.0);
        encoder.setPIDSourceType(PIDSourceType.kRate);
        
        lifterMotor = new Spark(3);
        addChild("lifterMotor",lifterMotor);
        lifterMotor.setInverted(false);
        
        ballLifter_PID = new PIDController(0.1, 0.0, 0.0, 0.0, encoder, lifterMotor, 0.02);
        addChild("ballLifter_PID",ballLifter_PID);
        ballLifter_PID.setContinuous(false);
        ballLifter_PID.setAbsoluteTolerance(0.2);

        ballLifter_PID.setOutputRange(-1.0, 1.0);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    final int pulsesPerRevolution = 7;                                  // The amount of pulses received after one full revolution of the motor.
    double gearRatio = 188;                                             // The gear ratio for the lifter motor
    double degreePerPulse = 360 / (gearRatio * pulsesPerRevolution);    // Finds how many degrees each pulse represents

    final double armHeight = 27.0;          // How hight up the pivot point of the arm is from the ground
    final double armLength = 17.0;          // The length of the arm

    // Method for moving the lift to the height of the Loading Station
    public void moveToLoading(){
        moveToHeight(44.5);
    }

        // Method for moving the lift to the height of the first ball level
    public void moveToFirst(){
        moveToHeight(27.5);
    }

    // Method for moving the lift to the height of the the second ball level
    public void moveToSecond(){
        moveToHeight(55.5);
    }

    /** Moves the arm to a set height that the 
     * 
     *  @param height the height that you want the arm to move to in inches
     */
    public void moveToHeight(double height){

        // double goal;

        // double adj = height - armHeight;



        // // Sets 
        // ballLifter_PID.setSetpoint(goal);
    }


    // Enables/disables the PID controller so it doesn't run 
    // while the operator is manually controlling the lift system
    public void enableIntervals(){
        if(ballLifter_PID.isEnabled()){
            ballLifter_PID.disable();
        }
        else{
            ballLifter_PID.enable();
        }
    }

    // Method to move the arm up at a set speed
    public void moveArmUp(){
        lifterMotor.set(.5);
    }

    public void moveArmDown(){
        lifterMotor.set(-.5);
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

