// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Robot2019.subsystems;


import org.usfirst.frc4579.Robot2019.Robot;
import org.usfirst.frc4579.Robot2019.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class HatchLifter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Spark lifterMotor;
    private Encoder encoder;
    private PIDController hatchLifter_PID;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public HatchLifter() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        lifterMotor = new Spark(2);
        addChild("lifterMotor",lifterMotor);
        lifterMotor.setInverted(false);
        
        encoder = new Encoder(1, 2, true, EncodingType.k4X);
        addChild("encoder",encoder);
        encoder.setDistancePerPulse(1.0);
        encoder.setPIDSourceType(PIDSourceType.kRate);
        
        hatchLifter_PID = new PIDController(0.001, 0.0, 0.0, 0.02, encoder, lifterMotor, 0.5);
        addChild("hatchLifter_PID",hatchLifter_PID);
        hatchLifter_PID.setContinuous(false);
        hatchLifter_PID.setAbsoluteTolerance(0.2);

        hatchLifter_PID.setOutputRange(-1.0, 1.0);
        
        hatchLifter_PID.setSetpoint(10);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
        // encoder.setReverseDirection(true);
    }

    public String activeSide = "Hatch";    // Variable that stores whether the hatch or the cargo side is in use
                                            // Currently placed in this subsystem b/c it doesn't work in the main Robot class

    boolean usingIntervals = false;          // Whether the robot is moving based on intervals or the joystick throttle
    int intervalGoal = 0;                   // The current height interval that the robot is aiming for
    int[] totalGoals = {250,400};                     // The number of intervals the robot can switch between

    double P = 0.001;
    double I = 0.0;
    double D = 0.0;

    final int maxCount = 400;
    final double hatchHeight1 = 250;        // The height of the first hatch level in encoder counts
    final double hatchHeight2 = 500;        // The height of the second hatch level in encoder counts
    final double hatchTolerance = 30;       // How far off the encoder counts can be from the hatch

    final int pulsesPerRevolution = 7;                                          // The amount of pulses received after one full revolution of the motor.
    final double gearRatio = 188;                                               // The gear ratio for the lifter motor
    final double degreePerPulse = 360 / (gearRatio * pulsesPerRevolution);      // Finds how many degrees each pulse represents
    final double armHeight = 33.7;                                              // How hight up the pivot point of the arm is from the ground
    final double armLength = 17.0;                                              // The length of the arm

    // Thread that matches the PID lift system for the robot
    Thread liftThread = new Thread(()->{
        double endTime = 0;

        while(!Thread.interrupted()){
            double startTime = Timer.getFPGATimestamp();

            int error = totalGoals[intervalGoal] - encoder.get();
            double deltaTime = startTime - endTime;

            double speed = error * P + (error*deltaTime) * I + (error/deltaTime) * D;

            lifterMotor.set(speed);
            
            endTime = startTime;
            startTime = Timer.getFPGATimestamp();
        }
    });

    // Main method for the subsystem that should be called by the command
    public void moveHatchLifter(){
        if(usingIntervals){
            // moveToInterval();
        }
        else{
            // hatchLifter_PID.disable();
            // lifterMotor.stopMotor();

            moveManually();

            // Will print out a reminder if you are at your goal
            isAtGoal();
        }
    }

    // Moves the robot to set intervals
    public void moveToInterval(){
        if(!hatchLifter_PID.isEnabled()){
            hatchLifter_PID.disable();
        }
        
        SmartDashboard.putNumber("Hatch Encoder: ", encoder.get());
        
        if(Robot.oi.everyStick.getRawButtonPressed(4)){
            // Moves up an interval
            intervalGoal = ++intervalGoal % totalGoals.length;

            System.out.println("Current lift mode is: " + intervalGoal);
        }
        
        // Moves the ball lifter to its appropriate goal
        switch (intervalGoal){
            case 0:
                moveToFirst();
                break;
            case 1:
                moveToSecond();
                break;
            default:
                moveToFirst();
        }
     
        // if(Math.abs(encoder.get() - hatchHeight1) < hatchTolerance && intervalGoal == 0){
            
        // }
        // else if(Math.abs(encoder.get() - hatchHeight1) < hatchTolerance && intervalGoal == 1){

        // }
        // else{
        //     lifterMotor.stopMotor();;
        // }
    }

    // Method for moving the lift to the height of the first hatch level
    public void moveToFirst(){
        // double degree = Math.acos(14.7/armLength)*(180/Math.PI);
        // moveToDegree(degree);
        hatchLifter_PID.setSetpoint(150);
    }

    // Method for moving the lift to the height of the the second hatch level
    public void moveToSecond(){
        // double degree = Math.acos(7/armLength)*(180/Math.PI);
        // moveToHeight(degree+90);

        hatchLifter_PID.setSetpoint(-100);
    }

    /** Moves the arm to a set height
     * 
     *  @param height the height that you want the arm to move to in inches
     */
    public void moveToHeight(double height){
        // double goal = 0;

        // if(height > armHeight){

        // }
        // else{
        //     double adj = height - armHeight;
        // }

        // moveToDegree(goal);
    }

    
    public void moveToDegree(double degree){
        hatchLifter_PID.setSetpoint(degree / degreePerPulse);
    }

    // Enables/disables the PID controller so it doesn't run 
    // while the operator is manually controlling the lift system
    public void enableIntervals(){
        usingIntervals = !usingIntervals;
        if(!usingIntervals){
            System.out.println("Enabling Manual Control of the Hatch Lifter");
        }
        else{
            System.out.println("Disabling Manual Control of the Hatch Lifter");
        }
    }

    // Moves the lifter up and down at a set speed depending on whether
    // button #6 and 7 are pressed
    public void moveManually(){
        double speed = ((-Robot.oi.everyStick.getZ() + 1.0) / 4.0)+ .5;

        if(hatchLifter_PID.isEnabled()){
            hatchLifter_PID.disable();
        }

        if(Robot.oi.everyStick.getRawButton(6)){
            lifterMotor.setSpeed(.5 * speed);
            // System.out.println("Moving the hatch up");
        }
        else if(Robot.oi.everyStick.getRawButton(7)){
            lifterMotor.setSpeed(-.5 * speed);
            // System.out.println("Moving the hatch down");
        }
        else{
            lifterMotor.stopMotor();
        }
    }

    // Prints whether or not the robot is at its set heights
    public void isAtGoal(){
        if(Math.abs(encoder.get() - hatchHeight1) < 10){
            SmartDashboard.putString("At Goal: ", "First Hatch Level");
        }
        else if(Math.abs(encoder.get() - hatchHeight2) < 10){
            SmartDashboard.putString("At Goal: ", "First Hatch Level");
        }
        else{
            SmartDashboard.putString("At Goal: ", "Not Level");
        }
    }

    public void getEncoderCount(){
        System.out.println(encoder.get());
    }

    public void stop(){
        lifterMotor.stopMotor();
    }

    public void reset(){
        // hatchLifter_PID.setSetpoint(0);
        encoder.reset();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new moveHatchLifter());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

